// preguntas.js
const preguntas = [
  { pregunta: "¿Quién fue el primer hombre creado por Dios?", opciones: ["A) Adán", "B) Moisés", "C) Noé", "D) Abraham"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué significa el nombre 'Jesús'?", opciones: ["A) Salvador", "B) Rey de Reyes", "C) El Ungido", "D) Hijo de Dios"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cómo se llama la madre de Jesús?", opciones: ["A) Ester", "B) María", "C) Marta", "D) Sara"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué río cruzaron los israelitas cuando salieron de Egipto?", opciones: ["A) Jordán", "B) Nilo", "C) Mar Rojo", "D) Éufrates"], respuesta: "C", genero: "Biblia" },
  { pregunta: "¿Quién traicionó a Jesús?", opciones: ["A) Pedro", "B) Judas", "C) Juan", "D) Santiago"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿En qué ciudad nació Jesús?", opciones: ["A) Nazaret", "B) Jerusalén", "C) Belén", "D) Roma"], respuesta: "C", genero: "Biblia" },
  { pregunta: "¿Cuál es el primer libro del Antiguo Testamento?", opciones: ["A) Génesis", "B) Éxodo", "C) Levítico", "D) Deuteronomio"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué alimento descendió del cielo para alimentar al pueblo de Israel en el desierto?", opciones: ["A) Maná", "B) Pan", "C) Carne", "D) Frutas"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cómo se llama el discípulo amado de Jesús?", opciones: ["A) Pedro", "B) Juan", "C) Santiago", "D) Andrés"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué instrumento tocaba el rey David?", opciones: ["A) Flauta", "B) Harpa", "C) Guitarra", "D) Tambor"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿En qué se convirtió Saulo después de su encuentro con Jesús?", opciones: ["A) Profeta", "B) Apóstol", "C) Rey", "D) Discípulo"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cómo se llama el padre de Juan el Bautista?", opciones: ["A) Zacarías", "B) José", "C) Simón", "D) Elías"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cuál es el último libro del Nuevo Testamento?", opciones: ["A) Judas", "B) Apocalipsis", "C) Hechos", "D) Romanos"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué hizo Moisés para liberar al pueblo de Israel?", opciones: ["A) Derribó las murallas de Jericó", "B) Partió el Mar Rojo", "C) Detuvo el sol", "D) Invocó el maná"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cómo se llamaba el hermano de Moisés?", opciones: ["A) Aarón", "B) Josué", "C) Samuel", "D) Isaac"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué rey construyó el Templo de Jerusalén?", opciones: ["A) Salomón", "B) David", "C) Ezequías", "D) Acaz"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué milagro hizo Jesús en las bodas de Caná?", opciones: ["A) Sanó a un ciego", "B) Caminó sobre el agua", "C) Multiplicó los panes y los peces", "D) Convirtió el agua en vino"], respuesta: "D", genero: "Biblia" },
  { pregunta: "¿Quién fue el profeta que desafió a los 450 profetas de Baal?", opciones: ["A) Isaías", "B) Elías", "C) Jeremías", "D) Ezequiel"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué hombre vivió en el vientre de un gran pez durante tres días?", opciones: ["A) Noé", "B) Jonás", "C) Elías", "D) Moisés"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cuál es el versículo más corto de la Biblia?", opciones: ["A) Jesús lloró", "B) Ama a tu prójimo", "C) El Señor es mi pastor", "D) Yo soy el camino"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué rey escribió muchos de los Proverbios?", opciones: ["A) David", "B) Salomón", "C) Ezequías", "D) Josías"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cuál de los apóstoles negó a Jesús tres veces antes del amanecer?", opciones: ["A) Juan", "B) Pedro", "C) Andrés", "D) Tomás"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué ciudad fue destruida por fuego y azufre debido a su pecado?", opciones: ["A) Nínive", "B) Babilonia", "C) Sodoma", "D) Jerusalén"], respuesta: "C", genero: "Biblia" },
  { pregunta: "¿Cuál fue el último milagro de Jesús antes de su crucifixión?", opciones: ["A) Sanó a un ciego", "B) Resucitó a Lázaro", "C) Sanó a un leproso", "D) Curó a un soldado"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cuántos días estuvo Jesús en el desierto antes de ser tentado?", opciones: ["A) 30", "B) 40", "C) 50", "D) 3"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cómo se llama el lugar donde Jesús fue crucificado?", opciones: ["A) Gólgota", "B) Getsemaní", "C) Monte Sinaí", "D) Tabor"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cuántos apóstoles tenía Jesús?", opciones: ["A) 12", "B) 10", "C) 15", "D) 7"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué profeta fue tragado por un pez gigante?", opciones: ["A) Jonás", "B) Moisés", "C) Elías", "D) Daniel"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿En qué montaña recibió Moisés las tablas de la ley?", opciones: ["A) Monte Sinaí", "B) Monte Ararat", "C) Monte Nebo", "D) Monte Hermón"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué mujer dio a luz a Samuel?", opciones: ["A) Ana", "B) Elisabet", "C) Rebeca", "D) Sara"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué significa 'Mesías'?", opciones: ["A) Príncipe", "B) Salvador", "C) Rey", "D) Ungido"], respuesta: "D", genero: "Biblia" },
  { pregunta: "¿Qué mujer se convirtió en estatua de sal?", opciones: ["A) Sara", "B) Rebeca", "C) Lot", "D) La esposa de Lot"], respuesta: "D", genero: "Biblia" },
  { pregunta: "¿Qué personaje bíblico fue conocido por su gran sabiduría?", opciones: ["A) David", "B) Salomón", "C) Moisés", "D) Job"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Cómo se llamaba la esposa de Abraham?", opciones: ["A) Sara", "B) Rebeca", "C) Lea", "D) Raquel"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Quién fue el primero en ver a Jesús resucitado?", opciones: ["A) Pedro", "B) María Magdalena", "C) Juan", "D) Tomás"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué animal habló con el profeta Balaam?", opciones: ["A) Burro", "B) Caballo", "C) Camello", "D) León"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Quién bautizó a Jesús?", opciones: ["A) Pedro", "B) Juan el Bautista", "C) Moisés", "D) Santiago"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué hijo de Jacob fue vendido por sus hermanos?", opciones: ["A) José", "B) Benjamín", "C) Rubén", "D) Simeón"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cuántos años vivió Noé?", opciones: ["A) 100", "B) 500", "C) 600", "D) 800"], respuesta: "C", genero: "Biblia" },
  { pregunta: "¿Cuál de los discípulos era conocido como el 'Doble'?", opciones: ["A) Tomás", "B) Andrés", "C) Felipe", "D) Mateo"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿A quién le habló Dios desde una zarza ardiente?", opciones: ["A) Moisés", "B) David", "C) Samuel", "D) Elías"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué rey hizo construir un altar al dios Baal?", opciones: ["A) Acab", "B) David", "C) Salomón", "D) Josías"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué hijo de Adán y Eva mató a su hermano?", opciones: ["A) Caín", "B) Abel", "C) Set", "D) Enós"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué profeta fue llevado al cielo en un carro de fuego?", opciones: ["A) Elías", "B) Isaías", "C) Jeremías", "D) Ezequiel"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué discípulo dudó de la resurrección de Jesús?", opciones: ["A) Juan", "B) Pedro", "C) Tomás", "D) Andrés"], respuesta: "C", genero: "Biblia" },
  { pregunta: "¿Cuántos días duró el diluvio?", opciones: ["A) 10", "B) 20", "C) 30", "D) 40"], respuesta: "D", genero: "Biblia" },
  { pregunta: "¿A qué profeta le dijo Dios que fuera a Nínive?", opciones: ["A) Isaías", "B) Jonás", "C) Jeremías", "D) Ezequiel"], respuesta: "B", genero: "Biblia" },
  { pregunta: "¿Qué mujer fue la madre de Isaac?", opciones: ["A) Sara", "B) Rebeca", "C) Raquel", "D) Lea"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Cuántos mandamientos dio Dios a Moisés?", opciones: ["A) 10", "B) 15", "C) 12", "D) 7"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué rey destruyó las murallas de Jericó?", opciones: ["A) Josué", "B) David", "C) Salomón", "D) Ezequías"], respuesta: "A", genero: "Biblia" },
  { pregunta: "¿Qué significa el nombre 'Emmanuel'?", opciones: ["A) Dios con nosotros", "B) Rey eterno", "C) Libertador", "D) Fuerza de Dios"], respuesta: "A", genero: "Biblia" }
];
